config/routes.rb
SdtExpress::Application.routes.draw do
  root to: 'home#index'

  resources :users

  get 'orders/search'
  resources :orders

  resources :drivers

  get "home/index"

  resources :news_items

end

app/models/driver.rb
# coding: utf-8

class Driver < ActiveRecord::Base
  attr_accessible :current_loc, :name, :vehicle_status, :vehicle_type
  default_scope order('updated_at DESC')
  def vehicle_type_readable
    type_mapper = {
      0 => '拖拉机',
      1 => '电动车',
      2 => '三轮车'
    }

    return type_mapper[self.vehicle_type]
  end

  def vehicle_status_readable
    status_mapper = {
      false => '空闲',
      true => '忙碌'
    }

    return status_mapper[self.vehicle_status]
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @drivers }
    end
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.json
  def new
    @driver = Driver.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(params[:driver])

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render json: @driver, status: :created, location: @driver }
      else
        format.html { render action: "new" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.json
  def update
    @driver = Driver.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to drivers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for @driver, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vehicle_type, :class => 'control-label' %>
    <div class="controls">
      <%#= f.number_field :vehicle_type, :class => 'number_field' %>
      <%= f.select :vehicle_type, ['拖拉机', '电动车', '三轮车'].each_with_index.map{|type, i| [type, i]} %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_loc, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_loc, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :vehicle_status, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :vehicle_status, :class => 'check_box' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                drivers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/drivers/index.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:vehicle_type) %></th>
      <th><%= model_class.human_attribute_name(:current_loc) %></th>
      <th><%= model_class.human_attribute_name(:vehicle_status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= link_to driver.id, driver_path(driver) %></td>
        <td><%= driver.name %></td>
        <td><%= driver.vehicle_type_readable %></td>
        <td><%= driver.current_loc %></td>
        <td><%= driver.vehicle_status_readable %></td>
        <td><%=l driver.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_driver_path(driver), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      driver_path(driver),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_driver_path,
            :class => 'btn btn-primary' %>

app/views/drivers/new.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/drivers/show.html.erb
<%- model_class = Driver -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @driver.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vehicle_type) %>:</strong></dt>
  <dd><%= @driver.vehicle_type %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_loc) %>:</strong></dt>
  <dd><%= @driver.current_loc %></dd>
  <dt><strong><%= model_class.human_attribute_name(:vehicle_status) %>:</strong></dt>
  <dd><%= @driver.vehicle_status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              drivers_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_driver_path(@driver), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              driver_path(@driver),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>